### ISSUE TITLE
FormulaGrader should have an `allow_inf` key but it does not

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mitx-grading-library#103]
In calc.py, evaluator has an `allow_inf` key. FormulaGrader should have a configuration option for that.

I think we meant to do this, but it got lost somewhere.

**Comment by jolyonb** [comment]
No, this was actually purposeful. The `allow_inf` key was added so that `IntegralGrader` could have infinite bounds. Do you think we should allow infinity in a formula?

**Comment by ChristopherChudzicki** [comment]
No, that's fine.

I wasn't really sure. I just discovered that it didn't while investigating #104.

I'm going to close.
