### ISSUE TITLE
Request for variable names with superscripts

### ISSUE THREAD

**Issue by jolyonb** [mitodl/mitx-grading-library#11]
See title! Not obvious how you'd implement this...

**Comment by ChristopherChudzicki** [comment]
Curious: What's the use-case? Tensor notation? Superscript notation for derivatives? Do people just want `f^2`, or will they way `f^(2,1)` as a variable also?

First: Certainly if `x^2` is a variable, then `x` should not be a variable also, so we'd have to add some validation for the schema. (I suppose that if `f^2` is a function, `f` could also be a function).

Here are two possible thoughts for implementation:

-  Pre-process the user-submission before passing it to the parser. That is, replace all instances of the declared variable `x^2` with a valid (unused) variable like (`x1`). This might complicate sampling and error messages. This seems a bit messy.
- Alter the parser based on the grader configuration. For example, if `x^2` and `y^2` are declared as variables, alter the parser to use

```python
superscript_vars = ['x^2', 'y^2'] # would be passed as an argument
inner_varname = Combine(
    Or(superscript_vars) |
    (
     Word(alphas + "_", alphanums + "_") +
     ZeroOrMore("'")
    )
)
```

This correctly recognizes `a^2` as "a squared", but treats `x^2` and `y^2` as single variables:

```XML
<sum>
  <product>
    <parallel>
      <power>
        <atom>
          <variable>
            <ITEM>a</ITEM>
          </variable>
        </atom>
        <ITEM>^</ITEM>
        <atom>
          <number>
            <ITEM>2</ITEM>
          </number>
        </atom>
      </power>
    </parallel>
  </product>
  <ITEM>+</ITEM>
  <product>
    <parallel>
      <power>
        <atom>
          <variable>
            <ITEM>y^2</ITEM>
          </variable>
        </atom>
      </power>
    </parallel>
  </product>
  <ITEM>+</ITEM>
  <product>
    <parallel>
      <power>
        <atom>
          <variable>
            <ITEM>x^2</ITEM>
          </variable>
        </atom>
      </power>
    </parallel>
  </product>
</sum>
```

Caveat about the second approach: The order of parsing terms in inner_varname seems to be important—superscript_vars needs to come before the normal variables—and I do not completely understand why that is yet.

**Comment by jolyonb** [comment]
Simona wanted to have tensor notation. I'm not sure if she wanted abstract index notation or just specific component notation. I was thinking something like a^{ijk} might be possible, using the curly braces to specify that indices were coming.

**Comment by jolyonb** [comment]
I haven't checked how asciimath parses a^{ijk} though. On a related note, did you know that "oo" in asciimath renders infinity? Do we want to add that to the integral grader?

**Comment by ChristopherChudzicki** [comment]
Your idea is much simpler, and I believe it displays correctly (at least in textline math). I like it!
