### ISSUE TITLE
MJxPrep needs better error handling

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mitx-grading-library#117]
Consider the following typing:

```
                        // displays as:
cross(a,b) + fact       // a x b + fact
cross(a,b) + fact(      // cross(a,b) + fact(
cross(a,b) + fact(5     // cross(a,b) + fact(5
cross(a,b) + fact(5)    // a x b + 5!
```

errors in one part of a string should not prevent display of the rest.

I have a plan, but finishing column vector display first.

**Comment by jolyonb** [comment]
Yeah, I saw this. It could definitely be improved, but it's a bit trickier than I want to deal with in javascript! All yours :-)
