### ISSUE TITLE
Negative Powers to Zero-Det Matrix Not Handled

### ISSUE THREAD

**Issue by jolyonb** [mitodl/mitx-grading-library#131]
If you raise a matrix with zero determinant to a negative power, the raw error from `np.linalg.pow` is raised, rather than catching the error beforehand and presenting a nice error message.

**Comment by ChristopherChudzicki** [comment]
Good point. Probably a simple try/catch in MathArray's pow method.

**Comment by ChristopherChudzicki** [comment]
@jolyonb We had talked about rolling this into #134, but I did not address it yet. Partly because it seems separate issue, but mostly because #134 is ready for review and I should work on my classes :)

But if this is causing problems for anyone you know of, let me know and I'll make the time soon.

**Comment by jolyonb** [comment]
No, no rush at all.

**Comment by ChristopherChudzicki** [comment]
@jolyonb I should have deleted that comment :) I decided it was easy and so I did it. #136

**Comment by jolyonb** [comment]
Ah, I started with the earliest email from you and began working my way up ;-)
