### ISSUE TITLE
atan2

### ISSUE THREAD

**Issue by jolyonb** [mitodl/mitx-grading-library#133]
Would be good to have an arctangent function that accepts an x and a y value, capable of returning results in all four quadrants.

**Comment by ChristopherChudzicki** [comment]
Sure!  Is this just “it would be nice” or is there a class you have a specific purpose in mind for?  Do you care what the name is? We could overload ‘arctan(...)’ so that except one or two arguments (This is what Mathematica does) or have a separate function.

**Comment by jolyonb** [comment]
I'm not sure we have the infrastructure to overload a function at this stage? I'm not sure we really need it, either... `atan2` is a fine function name (used by various codes). And yes, I have an explicit use for it in computing quantum phases.

**Comment by jolyonb** [comment]
Resolved by #139
