### ISSUE TITLE
Implement grading for non-textbox problems

### ISSUE THREAD

**Issue by jolyonb** [mitodl/mitx-grading-library#142]
Dropdown/Multiple Choice/Checkbox problems can all be handled by a grader. So far, we haven't attempted to do this (mostly because it's handled perfectly ok by edX), but with the introduction of attempt-based grading, it would be useful to have these. We could also implement various partial credit options for Checkbox problems.

**Comment by ChristopherChudzicki** [comment]
> Dropdown/Multiple Choice/Checkbox problems can all be handled by a grader.

Are you sure about this? But I remember customresponse being pretty limited in its response types. Here's what I believe is the relevant line in `responsetypes.py`:

https://github.com/edx/edx-platform/blob/master/common/lib/capa/capa/responsetypes.py#L2087

I haven't tried on edX platform in years, but I remember this being an issue for me when I was working on online lab activities.

**Comment by jolyonb** [comment]
Hrmm. I believe you're right. Grumble. And Michelle was so looking forward to attempt based grading on multiple choice...

So, part of the issue seems to be that radioresponse/checkbox/dropdown all do some XML processing to be able to produce the list of answers and true/false things. This would be annoying, because you'd then need to have true/false list twice. Grumblesigh.

Ok, maybe I need to think on this a bit more... Perhaps we can have a hint function to modify the score based on the attempt number? I don't know if the hint function can be given access to the attempt number though sigh...

**Comment by jolyonb** [comment]
Sigh. Can't expose attempt number to hint functions either. I guess this one has to go on ice :-(
