### ISSUE TITLE
Problems with unmatched parentheses

### ISSUE THREAD

**Issue by jolyonb** [mitodl/mitx-grading-library#147]
The javascript parser doesn't treat unmatched parentheses correctly when doing its wrapping. In particular, if you put in `sin(`, the output is `{:s:}in(`.

**Comment by ChristopherChudzicki** [comment]
So, the issue is that `{:s:}in(` displays as `s∈(`?

I think the behavior we want with unmatched parentheses is to wrap the function name only. So:

1. `sin(1/2` —> `{:sin:}(1/2`
2. `sin(1/2)` —> `{:sin(1/2):}`

does that sound right?

**Comment by jolyonb** [comment]
Yeah, I agree. That sounds good to me.
