### ISSUE TITLE
Keeping python_lib.zip up-to-date

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mitx-grading-library#17]
After merging a few recent PRs, I don't think python_lib.zip is up-to-date anymore. (E.g., #15).

What's our general philosophy on this? Should the primary author of PR not worry about it, and it's the merger's responsibility to update python_lib.zip just before merge? Could we possibly add a test that checks if python_lib.zip is up-to-date, so that travis warns us if we forget?

**Comment by jolyonb** [comment]
Hah, I was just writing an email to you regarding this! This is intimately related to the issue of versioning. Do we want to update to 1.0.1 now, for example? Do we want to keep a changelog? We can write a travis test that checks the version in the zip file, but I think that's going to be annoying more than anything else. I'll propose periodically updating the zip file and change log, and updating the version too.

**Comment by jolyonb** [comment]
Resolved by #18, which sets the protocol for the future too!
