### ISSUE TITLE
Using MatrixGrader for noncommutative algebra: confusing error messages

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mitx-grading-library#183]
Sometimes we want to grade mathematical expressions with noncommutative variables (for example, operators in quantum mechanics). `MatrixGrader` provides a natural way to do this, but matrix-related error messages might be confusing to students.

Some possible ways to resolve this issue:
- **Option 1:** Completely disable matrix-related error messages (#158 does this partially, just for ShapeErrors)
- **Option 2:** Customize the error messages, see below.

Expanding on Option 2, I am imagining something like this:

```python
from mitxgraders import *
grader = MatrixGrader(
    variables=['A'],
    sample_from={
        'A': RealMatrices(description='operator')
    }
)
# raises ShapeError: Cannot add/subtract scalars to a operator.
result = grader('A', '1 + A')
```

We actually have most of the infrastructure in place for a solution like this. MathArray instances have properties `shape_name` and `description` that are used to generate error messages. We just need to give authors a way to customize these names (if desired).

I like Option 2 a lot more than Option 1. Consider that in a QM course, a student might very reasonably submit `1 + A` where the answer is `Identity + A`. It would much better to give them specific feedback rather than just "incorrect".

@jolyonb What do you think?

**Comment by jolyonb** [comment]
I like the idea of option 2 in principle, but it will be a fair bit of work to do that (and I need something that works by next week!). I also don't see anything preventing us from having both options available. What do you think?

**Comment by jolyonb** [comment]
We decided that we didn't have a) the bandwidth to do this, or b) a good way to implement it in such a way that people would actually use it, so I'm closing this.
