### ISSUE TITLE
FormulaGrader constant multiple comparer

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mitx-grading-library#193]
In FormulaGrader problems, we'd like to be able to test whether the student input differs from expected input by a constant multiple ("linearly related").

A good solution to this problem should give:
 - full credit if student input is correct
 - no credit if student input is not linearly related to expected input
 - no credit if student input is zero (trivial linear relationship)
 - *configurable* partial credit if student input is linearly related to expected input

The problem is a bit difficult because currently comparer functions can only compare sample evaluation (student_input_eval & comparer_params_eval) one by one. To achieve the above, we need to compare ALL the evaluations at the same time.

Additionally, the solution should:
 - facilitate similar features in future (e.g., differ by additive constant)
 - use similar API as existing comparer functions (ideally, same API)

**Comment by jolyonb** [comment]
Resolved by #196.
