### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by jolyonb** [mitodl/mitx-grading-library#20]
We should probably have some special error catching for division by zero in calc.py. At the moment, students get a "Could not parse your formula" error, which is not very helpful.

**Comment by ChristopherChudzicki** [comment]
Yes, definitely! I am happy to look into it tomorrow, or you can procrastinate some more :).

**Comment by jolyonb** [comment]
I really can't afford to procrastinate, more, alas :-( Please feel free to give it a go! Note that it may break some of the tests, where I used div by zero as the only thing I could think of as a way of generating an uncaught exception in calc.py. I did later think of another way - define a user function that raises an exception!

**Comment by ChristopherChudzicki** [comment]
Resolved by #21
