### ISSUE TITLE
Comparers and import *

### ISSUE THREAD

**Issue by jolyonb** [mitodl/mitx-grading-library#202]
Is there a reason that comparers aren't included when you do `from mitxgraders import *`? I don't recall...

**Comment by ChristopherChudzicki** [comment]
No good reason. Happy to add them.

**Comment by jolyonb** [comment]
Ok, let's do so then. It's annoying to have to do a second line of imports when writing problems.

**Comment by ChristopherChudzicki** [comment]
K, I'll make a quick PR for it after #196

**Comment by jolyonb** [comment]
Resolved by #203.
