### ISSUE TITLE
Multiple Testing Environments and Joint Coverage

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mitx-grading-library#218]
TODO:
 - [x] run tests on Python 2 and Python 3
 - [x] generate a joint coverage report https://coverage.readthedocs.io/en/latest/cmd.html#combining-data-files

**Comment by jolyonb** [comment]
You'll need to use build stages in Travis to run `combine` after different tests complete: https://docs.travis-ci.com/user/build-stages/

**Comment by jolyonb** [comment]
codecov-io to the rescue!
