### ISSUE TITLE
Remove unnecessary parens from DiscreteSet constructor

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mitx-grading-library#236]
#235 made me think that we should implement an `__init__` method for `DiscreteSet`, instead of using `ObjectWithSchema`'s `__init__`:

```python
def __init__(self, *items):
        if len(items) == 1: # To maintain compatibility with DiscreteSet((1, 2, 3))
            self.config = self.validate_config(items[0])
        else:
            self.config = self.validate_config(items)
```
which would allow `DiscreteSet(1,2,3).

I guess it's annoying to have a separate init, but it's nice to get rid of extra parens.

Anyway, would just need to change a few docs.

**Comment by jolyonb** [comment]
Two words: backwards compatibility. Also, `FormulaGrader` coerces tuples into `DiscreteSet`s, so you never actually need to see the double parentheses. That doesn't seem to be documented though...

**Comment by ChristopherChudzicki** [comment]
@jolyonb Ah. Notice I did preserve backward compatibility 😛

**Comment by jolyonb** [comment]
Ah, indeed, you did. I think I'm happy with just relying on the coercion here regardless though.
