### ISSUE TITLE
fix warnings in pytest 3.7

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mitx-grading-library#244]
tests/formulagrader/test_formulagrader.py:681
  /Users/cchudzicki/Documents/dev/mitx-grading-library/tests/formulagrader/test_formulagrader.py:681: DeprecationWarning: invalid escape sequence \(
    "RealInterval\({u?'start': 1, u?'stop': 5}\)")

**Comment by jolyonb** [comment]
Looks like there's 54 warnings in the Travis output...

**Comment by ChristopherChudzicki** [comment]
Working on it now

**Comment by jolyonb** [comment]
Resolved by #246
