### ISSUE TITLE
Allow for tuples in expect values in a dictionary for itemgraders

### ISSUE THREAD

**Issue by jolyonb** [mitodl/mitx-grading-library#282]
I propose the following extension to the answers block for `ItemGrader`:

```
answers=(
    {'expect': ('multiple', 'answers', 'that', 'use', 'the', 'same', 'msg', 'and', 'grade_decimal'), 'grade_decimal': value, 'msg': 'Message here'},
    ...
)
```

I think this can be implemented by a simple tweak to `ItemGrader` and nothing else.

**Comment by jefrench** [comment]
Great idea!

**Comment by jolyonb** [comment]
Hah, you're the first to express any interest in this idea at all!
