### ISSUE TITLE
How can I add this library (mitxgraders) for my edX platform?

### ISSUE THREAD

**Issue by eazaika** [mitodl/mitx-grading-library#297]
There is no setup.py file anywhere.

**Comment by jolyonb** [comment]
This isn't a platform thing, it's an individual course thing. It gets loaded as a python library through the static assets of individual courses. This ensures that each course has the appropriate version that that course was written for.

See [our documentation](https://mitodl.github.io/mitx-grading-library/#loading-in-edx) for how to load the library.
