### ISSUE TITLE
I am installing this plugins with Tutor 13.2.2 on maple but getting this error

### ISSUE THREAD

**Issue by manojkumarhr** [mitodl/mitx-grading-library#316]
Collecting git+https://github.com/mitodl/mitx-grading-library.git (from -r ./private.txt (line 13))
  Cloning https://github.com/mitodl/mitx-grading-library.git to /tmp/pip-req-build-w5ffx8qj
  Running command git clone -q https://github.com/mitodl/mitx-grading-library.git /tmp/pip-req-build-w5ffx8qj
    ERROR: Command errored out with exit status 1:
     command: /openedx/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-w5ffx8qj/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-w5ffx8qj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-w5ffx8qj/pip-egg-info
         cwd: /tmp/pip-req-build-w5ffx8qj/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/pyenv/versions/3.8.12/lib/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-w5ffx8qj/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 22.1.1 is available.
You should consider upgrading via the '/openedx/venv/bin/python -m pip install --upgrade pip' command.
The command '/bin/sh -c cd /openedx/requirements/   && touch ./private.txt   && pip install -r ./private.txt' returned a non-zero code: 1
Error: Command failed with status 1: docker build -t docker.io/overhangio/openedx:13.2.2 /root/.local/share/tutor/env/build/openedx

Please guide me how to install this plugin into my openedx version with tutor

**Comment by insad** [comment]
You should install codejail first from https://github.com/eduNEXT/tutor-contrib-codejail, and test if it works, e.g. in the demo course.

On that same eduNEXT page, under "Additional Resources" you find a link to a zip file (course_codejail_example.tar.gz), this is exactly this grading library demo ready to be imported as a new course in Studio.
