### ISSUE TITLE
Exponentiation issue in calc.py

### ISSUE THREAD

**Issue by jolyonb** [mitodl/mitx-grading-library#43]
There is an issue with calc.py whereby exponentiation doesn't parse in the correct order. I can't remember exactly what the issue is, but I remember that we haven't fixed it.

**Comment by jolyonb** [comment]
Ok, good to have this documented. I looked at calc.py to see why this is happening... and it's baked somewhat strongly into the tree parser. We'd have to refactor that algorithm significantly :-(

**Comment by ChristopherChudzicki** [comment]
Resolved by #59
