### ISSUE TITLE
Matrix/Vector Sampling

### ISSUE THREAD

**Issue by jolyonb** [mitodl/mitx-grading-library#44]
We would like to be able to say that `A` is a matrix of a given size, and sample appropriately. Alternatively, `vecv` is a vector of a certain size. Students can then input vector math expressions.

* Error should be raised when objects don't line up appropriately.
* We should decide how multiplication works. Is a vector times a vector a dot product?
* The identity matrix will need to be treated carefully.
* Row vs column vectors will need to be decided upon.
* We will probably need to make a transpose operation available, preferably as `A^T`. If a transposition operation is available, then vectors can be defined as a row/column vector and all multiplications work appropriately (dot products become `v^T * v`, for example).
* Special matrix samplers can be constructed (symmetric, antisymmetic, orthogonal, traceless, etc).
* Do we want to define a Hermitian conjugate operation? `A^dagger`?

**Comment by ChristopherChudzicki** [comment]
I'll have PR for you about this one tomorrow.

**Comment by jolyonb** [comment]
Awesome! I'm honestly surprised at how fast all of this has come together...

**Comment by jolyonb** [comment]
We should probably expand the equality grader to first check to make sure that the input has the same dimensions as the answer!

**Comment by jolyonb** [comment]
I'm going to go ahead and close this too. The only bit here that hasn't been implemented/superseded is a number of specialty matrix samplers, but that deserves its own issue. I seem to recall that the equality comparer checks for shape match as its first order of business; correct me if I'm wrong.
