### ISSUE TITLE
Custom Response Test Script

### ISSUE THREAD

**Issue by jolyonb** [mitodl/mitx-grading-library#47]
It would be good to have a way to run through all of the problem files in an edX course, determine which of them contain python scripts, and make sure those scripts instantiate. We could also allow for a special comment to be included in a custom script that our script can then use to test that the grader actually works.

**Comment by ChristopherChudzicki** [comment]
Potentially useful: I wrote a class last summer to extract and run Python from edX XML last summer.

https://github.mit.edu/chudzick/jsinput-emulator/blob/master/problems.py

(Requires an MIT login.)

**Comment by jolyonb** [comment]
I'll point to my [edx XML cleaner](https://github.com/jolyonb/edx-xml-clean) as a better avenue to implement something like this.
