### ISSUE TITLE
EdX Errors with Python Newlines are Problematic

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mitx-grading-library#82]
Of course Python newline (`\n`) doesn't display correctly if used in edx XML. But if you use one in an error message, you get a traceback, too!

```python
def cfn(e, a):
    raise Exception("A \n B")
]]>
</script>
```
<img width="1370" alt="screen shot 2018-07-13 at 12 51 26 am" src="https://user-images.githubusercontent.com/9010790/42672933-efdc8764-8636-11e8-9445-040ee31252c1.png">

whereas with HTML newlines only:
```python
def cfn(e, a):
    raise Exception("A <br/> B")
]]>
</script>
```
<img width="1378" alt="screen shot 2018-07-13 at 12 51 19 am" src="https://user-images.githubusercontent.com/9010790/42672974-28f5a35a-8637-11e8-820d-038967666f68.png">

So ... that's weird.

Not a big problem for us, easily resolved by editing AbstractGrader's `__call__` method.

**Comment by jolyonb** [comment]
I could've sworn that we were doing that already, no?

**Comment by ChristopherChudzicki** [comment]
I thought so too, but we were only doing it in `'msg'` and `'overall_message'`, NOT errors.

**Comment by jolyonb** [comment]
Fair enough. I like issues like this that have a one-liner fix!

**Comment by jolyonb** [comment]
Hmm. Apparently if you put "Resolves #issuenumber" in the PR description, when merged, it closes the issue automatically. But not if you put it in comments. Ah well.
