### ISSUE TITLE
Issue with row*column multiplication

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mitx-grading-library#89]
MathArray multiplication behaves ... unexpectedly...for row/column vectors:

```
a = MathArray([1, 2, 3]) # row: shape(1, 3)
b = MathArray([[1], [2], [3]]) # column: shape (3, 1)

(a*b).size # (1, 1)... a matrix with 1 row and 1 column
(a*b)*b # raises a ShapeError since (1,1) * (3, 1) does not work.
```

Relevant: MathArray mostly uses `np.dot` for multiplication, the documentation for which is very good: https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html (Note that the documentation is for v1.13, we use 1.6. But I don't think `dot` has changed. It references `matmul` as preferred over `dot`, which does not exist in 1.6)

Suggested fix: MathArray's `__mul__` method has some checks to see if self or other has `ndim=0`. These checks should actually be self or size has `size=0`.

Documentation for numpy.ndarray.size: 

https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.size.html

**Comment by jolyonb** [comment]
Ok, this looks gnarly. Can I leave it in your capable hands?
