### ISSUE TITLE
SpecifyDomain and row vs col vs vec

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mitx-grading-library#90]
If the domain is specified as 3-component vectors, then matrices of shapes `(3, 1)` and (1, 3)` will be rejected.

Is this the behavior that we want?

**Comment by jolyonb** [comment]
Hang on... is `[1,2,3]` a vector? Are `[[1, 2, 3]]` and `[[1], [2], [3]]`? matrices? Can a vector get transposed?

**Comment by jolyonb** [comment]
Inside the parsing routine `handle_node`, all of the children are computed. Perhaps we should check the children, and convert `[[1]] -> [1] -> 1` etc?

**Comment by ChristopherChudzicki** [comment]
I'm going to close this issue as I think it is resolved (or heavily mitigated) by discussion in #78 : 

>Actually: Let's just treat rows and columns as different things. For grading purposes, and for domain issues. (So, cross would only accept vectors, not rows or columns.)
>
>If you're worried that the answer is [1, 2, 3] and a student might enter [[1, 2, 3]], then just set max_array_dim=1. (I am thinking 1 should actually be the default. I suspect that vector-entry will be much more common than matrix-entry.)

At worst, students will get (reasonably instructive) error messages.

**Comment by ChristopherChudzicki** [comment]
@jolyonb Re:

> Inside the parsing routine handle_node, all of the children are computed. Perhaps we should check the children, and convert [[1]] -> [1] -> 1 etc?

We Converting [1] -> 1 in eval_array means that entrering a single-column matrix by hand would be literally impossible. I'm not sure that's the behavior we want.

I'll try articulating the current distinction between single-row, single-column, and vector arrays in the documentation, and if it doesn't make sense, we can revisit more. But I think it will make sense, and I think by-hand matrix entry will be pretty rare, so default of `max_array_dim=1` solves most issues.

**Comment by jolyonb** [comment]
Ah, I think I didn't articulate myself well here. I meant something more like the following:

```python
if all(i == 1 for i in array.shape):
    collapse(array)
```

So, if a number is literally just a 1x1x1x1x1x1x1x1x1x1x1x1x1x1x1x1x1x1 array, collapse it to a number?

**Comment by jolyonb** [comment]
Hmm. Yes, you're right. I suspect that we want to retain the ability to have rows and columns. Hopefully this won't be an issue all that often.

**Comment by jolyonb** [comment]
I'm going to go ahead and close this. I suspect that most problems associated with attempting to push the evaluator beyond its limits in this regards will arise from students not performing necessary simplifications. The students will just get an error message, anyway.
