### ISSUE TITLE
Tensor Products

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mitx-grading-library#96]
MatrixGrader does not currently support tensor product (aka Kronecker product).  This would certain be very very useful for a quantum information course.

@jolyonb Do any of the existing/planned QM series need this?

**Comment by jolyonb** [comment]
Not that I can think of. It may be useful for relativity courses to be able to contract appropriate indices though.

**Comment by jolyonb** [comment]
I'm going to close this issue as well. Nobody is requesting it, and we're not going to get to it in the time we have left.
